### ISSUE TITLE
Add instruction

### ISSUE THREAD

**Issue by mrded** [alexbaumgertner/sails-hook-bem-render#2]
It would be nice to have some instruction.

Thanks.

**Comment by mrded** [comment]
Just following current instruction. If my version of sails is 0.11.0 - should I create api/hooks/bem-render/index.js file at all?

**Comment by mrded** [comment]
After first run it gave me following error:

```
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory 'views/desktop.bundles/merged/merged.bemtree.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Hook.initialize (node_modules/sails-hook-bem-render/lib/index.js:20:30)
    at Hook.bound [as initialize] (sails/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at node_modules/sails/lib/hooks/index.js:74:14
    at node_modules/sails/node_modules/async/lib/async.js:454:17
    at node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete (node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

When I create empty views/desktop.bundles/merged/merged.bemtree.js file, it gave me the following: 

```
module.js:338
    throw err;
    ^
Error: Cannot find module 'views/desktop.bundles/merged/merged.bemhtml.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Hook.initialize (node_modules/sails-hook-bem-render/lib/index.js:22:27)
    at Hook.bound [as initialize] (node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at node_modules/sails/lib/hooks/index.js:74:14
    at node_modules/sails/node_modules/async/lib/async.js:454:17
    at node_modules/sails/node_modules/async/lib/async.js:444:17
    at Array.forEach (native)
    at _each (node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Immediate.taskComplete (node_modules/sails/node_modules/async/lib/async.js:443:13)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Once I create empty views/desktop.bundles/merged/merged.bemtree.js file, errors stops.

I think you should somehow mention in documentation about views/desktop.bundles/merged folder.

**Comment by alexbaumgertner** [comment]
"If my version of sails is 0.11.0 - should I create api/hooks/bem-render/index.js file at all?" – No, since 0.11 sails automatically find hooks.

**Comment by mrded** [comment]
In that case following instructions are really confusing:
- create `bem-render` folder in `api/hooks`
- create `index.js` file in `api/hooks/bem-render/`
- (sails < 0.11) write in `api/hooks/bem-render/index.js` this:

``` js
   module.exports = require('sails-hook-bem-render');
```

**Comment by alexbaumgertner** [comment]
@mrded thanks for notice, I removed it in https://github.com/alexbaumgertner/sails-hook-bem-render/pull/3

**Comment by mrded** [comment]
Great, looks much better! :) I'm going to try it tonight.

**Comment by mrded** [comment]
Before running `node_modules/.bin/enb make -d views --no-cache` you forgot to mention, that you need to install **enb** first.

I guess it should be like this: `npm i enb enb-bem enb-borschik enb-stylus enb-autoprefixer enb-diverse-js enb-modules enb-bemxjst enb-bem-techs --save`

Even after that, I'm getting errors:

```
$ node_modules/.bin/enb make -d views --no-cache
23:10:27.896 - build started
23:10:27.934 - [deprecated] [desktop.bundles/merged/merged.deps.js] Tech enb/techs/deps-merge is deprecated. Install package enb-bem-techs and use tech enb-bem-techs/techs/merge-deps instead.
23:10:27.938 - [deprecated] [desktop.bundles/merged/index.deps.js] Tech enb/techs/deps-provider is deprecated. Install package enb-bem-techs and use tech enb-bem-techs/techs/provide-deps instead.
23:10:27.939 - [rebuild] [desktop.bundles/index/index.bemdecl.js] file-provider
23:10:27.945 - [failed] [desktop.bundles/index/index.levels] levels
23:10:27.945 - [failed] [desktop.bundles/merged/merged.levels] levels
23:10:27.945 - [failed] [desktop.bundles/index/index.files] files
23:10:27.945 - [failed] [desktop.bundles/index/index.deps.js] deps-old
23:10:27.945 - [failed] [desktop.bundles/index/index.bemhtml.files] files
23:10:27.945 - [failed] [desktop.bundles/merged/merged.files] files
23:10:27.945 - [failed] [desktop.bundles/merged/merged.bemhtml.files] files
23:10:27.946 - [failed] [desktop.bundles/index/index.bemtree.js] bemtree
23:10:27.946 - [failed] [desktop.bundles/index/index.bemhtml.js] bemhtml
23:10:27.946 - [failed] [desktop.bundles/index/index.noprefix.css] css-stylus
23:10:27.946 - [failed] [desktop.bundles/index/index.browser.js] browser-js
23:10:27.946 - [failed] [desktop.bundles/index/index.browser.bemhtml.js] bemhtml
23:10:27.947 - [failed] [desktop.bundles/merged/merged.bemtree.js] bemtree
23:10:27.947 - [failed] [desktop.bundles/merged/merged.bemhtml.js] bemhtml
23:10:27.947 - [failed] [desktop.bundles/merged/merged.noprefix.css] css-stylus
23:10:27.947 - [failed] [desktop.bundles/merged/merged.browser.js] browser-js
23:10:27.947 - [failed] [desktop.bundles/merged/merged.browser.bemhtml.js] bemhtml
23:10:27.947 - [failed] [desktop.bundles/merged/index.deps.js] deps-provider
23:10:27.948 - [failed] [desktop.bundles/merged/merged.deps.js] deps-merge
23:10:27.948 - build failed
23:10:27.948 - [failed] [desktop.bundles/index/index.css] css-autoprefixer
23:10:27.949 - [failed] [desktop.bundles/merged/merged.css] css-autoprefixer
23:10:27.949 - [failed] [desktop.bundles/index/index.pre.js] file-merge
23:10:27.949 - [failed] [desktop.bundles/merged/merged.pre.js] file-merge
23:10:27.949 - build failed
Error: ENOENT, no such file or directory 'views/libs/bem-core/common.blocks'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at module.exports.inherit.load (node_modules/enb-bem/lib/levels/level.js:211:28)
    at node_modules/enb-bem/techs/levels.js:105:38
    at Array.map (native)
    at node_modules/enb-bem/techs/levels.js:104:42
    at Array.<anonymous> (node_modules/enb/node_modules/vow/lib/vow.js:202:56)
    at Immediate.callFns [as _onImmediate] (node_modules/enb/node_modules/vow/lib/vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I think it because you forgot to mention about **bower** installation.

**Comment by alexbaumgertner** [comment]
Oh, I see... I assumed that user had been working with BEM yet :)
I'll add some information for beginners :)

**Comment by alexbaumgertner** [comment]
@mrded I've added info about dependencies, look at https://github.com/alexbaumgertner/sails-hook-bem-render/blob/feature/documentation/README.md please :)
